---
title: "Zipkin model"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Define the model:
```{r}
model_str <- "
  model {
    # Initialize the model for k = 1
    m[1] ~ dpois(gamma * n[2, 1])         # number of new births
    t[1] ~ dbin(phi, z[1, 1])             # number of juveniles -> adults
    for (i in 1:2) {                      # i = 1 for juveniles, 2 for adults
      n[i, 1] ~ dpois(lambda[i])          # abundance
      y[i, 1] ~ dbin(rho[i], n[i, 1])     # number of observed individuals
      z[i, 1] ~ dbin(delta[i], n[i, 1])   # number of survivors
    }
  
    # Define the model for k > 1
    for (k in 2:K) {
      m[k] ~ dpois(gamma * n[2, k])
      t[k] ~ dbin(phi, z[1, k])
      n[1, k] <- m[k - 1] + z[1, k - 1] - t[k - 1]
      n[2, k] <- z[2, k - 1] + t[k - 1]
      for (i in 1:2) {
        y[i, k] ~ dbin(rho[i], n[i, k])
        z[i, k] ~ dbin(delta[i], n[i, k])
      }
    }
  }
"
model_conn <- textConnection(model_str)
```

Run JAGS and obtain samples:
```{r, message=FALSE, results='hide'}
library(rjags)

# Libraries for plotting
library(dplyr)
library(tidyr)
library(lazyeval)
library(ggplot2)

# Create dummy data
lambda <- c(30, 200)         # avg initial abundance of (juveniles, adults)
delta <- c(0.5, 0.7)         # survival probabilities of (juveniles, adults)
rho <- c(0.4, 0.8)           # detection probabilities of (juveniles, adults)
gamma <- 0.1                 # birth rate
phi <- 0.3                   # juvenile -> adult transition probability

K <- 10
n <- matrix(rep(NA, K * 2), nrow = 2)
z <- matrix(rep(NA, K * 2), nrow = 2)
m <- rep(NA, K)
t <- rep(NA, K)
for (k in 1:K) {
  if (k == 1) {
    n[, k] <- rpois(2, lambda)
  } else {
    n[, k] <- c(m[k - 1] + z[1, k - 1] - t[k - 1], z[2, k - 1] + t[k - 1])
  }
  
  z[, k] <- rbinom(2, n[, k], delta)
  m[k] <- matrix(rpois(1, gamma * n[2, k]))
  t[k] <- matrix(rbinom(1, z[1, k], phi))
}
y <- matrix(rbinom(K * 2, n, rho), 2)

# Initialize values
z0 <- y

# Run JAGS
model <- jags.model(model_conn,
                    data = list('y' = y, 'K' = k, 'lambda' = lambda,
                                'delta' = delta, 'rho' = rho,
                                'gamma' = gamma, 'phi' = phi),
                    inits = list('z' = z0),
                    n.chains = 1,
                    n.adapt = 1000)

samples <- coda.samples(model, c('n'), n.iter = 10000, thin = 20)
```

Plot the cumulative mean vs iteration of `n` at each life stage and time step `k`:

```{r}
# Preprocess for ggplot
samples_df <- data.frame(samples[[1]], iter = 1:nrow(samples[[1]]))
colnames(samples_df) <- gsub('\\.', '', colnames(samples_df))
samples_df <- samples_df %>%
  gather(var_k, value, -iter) %>%
  separate(var_k, into = c('var', 'stage', 'k'), sep = 1:2) %>%
  filter(var == 'n') %>%
  mutate(stage = ifelse(stage == 1, 'juvenile', 'adult')) %>%
  group_by(stage, k) %>%
  mutate(cum_mean = cumsum(value) / iter)
samples_df$k <- factor(samples_df$k, levels = 1:K)

# Juveniles
ggplot(samples_df %>% filter(stage == 'juvenile'), aes(iter, cum_mean, colour = k)) +
  geom_line() +
  theme_bw() +
  ggtitle('Mean vs iteration of juvenile n')

# Adults
ggplot(samples_df %>% filter(stage == 'adult'), aes(iter, cum_mean, colour = k)) +
  geom_line() +
  theme_bw() +
  ggtitle('Mean vs iteration of adult n')
```

Discard samples from iteration $\leq$ 100 and display the new mean and standard deviation of `n` at each life stage and time step:

```{r}
samples_df_new <- samples_df %>% filter(iter > 100)
summary <- samples_df_new %>% group_by(stage, k) %>%
  summarise(mean = mean(value), sd = sd(value))
```

```{r, echo = FALSE}
knitr::kable(summary)
```

Plot the distribution of `n` at each life stage and time step:

```{r}
for (stage in c('juvenile', 'adult')) {
  samples_stage <- samples_df_new %>% filter_(interp(~ stage == s, s = stage))
  for (k in 1:K) {
    samples_k <- samples_stage %>%
      filter_(interp(~ k == t_step, t_step = k))
    x_range <- min(samples_k$value):max(samples_k$value)
    plt <- ggplot(samples_k, aes(value)) +
      geom_bar() +
      geom_vline(aes(xintercept = mean(value)),
                 color = 'red', linetype = 'dashed') +
      scale_x_continuous(breaks = x_range) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
      ggtitle(paste0('Distribution of ', stage, ' n_', k))
    print(plt)
  }
}
```